### ISSUE TITLE
KeyError: 'sloc_count'

### ISSUE THREAD

**Issue by binglel** [Magic-Bubble/Mobike#1]
您好，最近在同样的算法解决交通问题，可以把写个较为详细的程序使用教程吗？
我试着运行了一下，构造样本已完成，接着是提取样本特征，出现问题，没有解决。希望您可以帮助一下，谢谢！

**Comment by janesunflower** [comment]
遇到同样的问题，请问解决了吗？

**Comment by janesunflower** [comment]
> 您好，最近在同样的算法解决交通问题，可以把写个较为详细的程序使用教程吗？
> 我试着运行了一下，构造样本已完成，接着是提取样本特征，出现问题，没有解决。希望您可以帮助一下，谢谢！

遇到同样的问题，请问解决了吗？

**Comment by binglel** [comment]
No
