### ISSUE TITLE
请问这个程序操作文档可以补充一下嘛？

### ISSUE THREAD

**Issue by 1412904892** [Magic-Bubble/Mobike#2]

**Comment by Magic-Bubble** [comment]
入口在main.py里，包括train,val和test，具体运行方法参见README

**Comment by 1412904892** [comment]
![image](https://user-images.githubusercontent.com/16586723/47912005-11ec5700-ded2-11e8-9950-bcfea6962f60.png)
这些注释掉的应该还是需要的吧，不然没有那个train_all = pd.read_hdf('/home/xuwenchao/dyj-storage/all-feat/feat_23_24_label.hdf')就找不到这个文件

**Comment by 1412904892** [comment]
可以回复一下吗

**Comment by Magic-Bubble** [comment]
对，当时是为了防止每次生成特征太慢，就先进行写文件操作，如果有这个文件的话，就可以注释掉那一句，如果没有，就需要先生成文件

**Comment by Miracleday23Kevin** [comment]
> 可以回复一下吗

请问你现在调用能跑通嘛？我这边还是没有，卡在几个hdf的生成不成功，feature提取不成功上

**Comment by Miracleday23Kevin** [comment]
> 对，当时是为了防止每次生成特征太慢，就先进行写文件操作，如果有这个文件的话，就可以注释掉那一句，如果没有，就需要先生成文件

你好，请问能再稍微给一下操作说明，或是另外云盘给到几个hdf和pickle文件么，现在浮现起来总会出现特征生成不成功，因为不少代码需要取消注释来用，谢谢！
